server:
  port: 9090
spring:
  cache:
    redis:
      cache-null-values: false
      time-to-live: 30000
      use-key-prefix: true
    type: redis
  datasource:
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      maximum-pool-size: 12
      minimum-idle: 5
    password: Mysql@1498
    url: jdbc:mysql://localhost:3306/articles
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: '7 '
        max-idle: 7
        max-wait: -1ms
        min-idle: 2
      shutdown-timeout: 200ms
    password: ''
    port: 6379
